<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="mass" value="10" /> <!-- arbitrary value for mass -->
    <xacro:property name="width" value="0.05" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height1" value="2" /> <!-- Link 1 -->
    <xacro:property name="height2" value="1" /> <!-- Link 2 -->
    <xacro:property name="height3" value="1" /> <!-- Link 3 -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}base_link" />
    </joint>

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height1}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height1}" />
        </geometry>
        <material name="blue" />
      </visual>

      <xacro:box_inertial x="${width}" y="${width}" z="${height1}" mass="${mass}">
        <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
      </xacro:box_inertial>
    </link>

    <joint name="${prefix}joint1" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}link1" />
      <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="1000" velocity="10.0" />
    </joint>

    <!-- Middle Link -->
    <link name="${prefix}link1">
      <collision>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height2}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height2}" />
        </geometry>
        <material name="red" />
      </visual>

      <xacro:box_inertial x="${width}" y="${width}" z="${height2}" mass="${mass}">
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0" />
      </xacro:box_inertial>
    </link>

    <joint name="${prefix}joint2" type="continuous">
      <parent link="${prefix}link1" />
      <child link="${prefix}link2" />
      <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="1000" velocity="10.0" />
    </joint>

    <!-- Top Link -->
    <link name="${prefix}link2">
      <collision>
        <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height3}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height3}" />
        </geometry>
        <material name="black" />
      </visual>

      <xacro:box_inertial x="${width}" y="${width}" z="${height3}" mass="${mass}">
        <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0" />
      </xacro:box_inertial>
    </link>

    <joint name="${prefix}tool_joint" type="fixed">
      <origin xyz="0 0 ${height3-axel_offset}" rpy="0 0 0" />
      <parent link="${prefix}link2" />
      <child link="${prefix}tool0" />
    </joint>

    <!-- Tool Link -->
    <link name="${prefix}tool0"/>

  </xacro:macro>
</robot>
